spring.application.name=fintrack-api

#MySql Config
spring.database.url = jdbc:mysql://localhost:3306/fintrack_db
spring.database.username = root
spring.database.password = VIJai@2006

#JPA/Hibernate Config
spring.jpa.hibernate.ddl-auto = update
spring.jpa.show-sql = true
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql = true

#Server Config
server.port = 8080